### ISSUE TITLE
Installation error "mrp_dynamic_line"

### ISSUE THREAD

**Issue by ska-ibees** [odoonz/odoonz-addons#2]
Hi, 
First of all thank you for sharing your knowledge and work with the community. 
Today I tried to install mrp_dynamic_line but got an error.
I was manage to install it by commenting demo file reference in manifest file.

"data": [
        "data/bom_line_xform.xml",
        "security/ir.model.access.csv",
        "views/mrp_bom.xml",
        "views/mrp_bom_line.xml",
        **# "demo/mrp_dynamic_line.xml"**
    ],
Error:
raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: product.product_category_5" while parsing /home/sb/web/sb.com/public_html/custom_addons/mrp_dynamic_line/demo/mrp_dynamic_line.xml:43, near
<record id="manu_product" model="product.product">
        <field name="name">Dishwasher</field>
        <field name="categ_id" ref="product.product_category_5"/>
        <field name="standard_price">1000.0</field>
        <field name="list_price">1750.0</field>
        <field name="type">consu</field>
        <field name="weight">100.0</field>
        <field name="uom_id" ref="product.product_uom_unit"/>
        <field name="uom_po_id" ref="product.product_uom_unit"/>
        <field name="attribute_value_ids" eval="[(6,0,[ref('mrp_dynamic_line.product_attribute_value_1')])]"/>
    </record>

**Comment by gdgellatly** [comment]
@go4site Thanks for using and reporting.  Must have been a late night adding those demo files.  Fixed it now.

**Comment by ska-ibees** [comment]
@gdgellatly Thank you indeed!
BTW, can mrp_dynamic_line be used along with Pledra's "Product configurator module"?
Can be is a stupid thing to ask :) 
Just asking if you have used it along with it? Any known issues?

**Comment by gdgellatly** [comment]
@go4site I'm not very familiar with the module, but I think it creates a new BoM for each variant.  This would possibly make it incompatible without some kind of glue or bridging module between the two.  

But I don't know.  Product configurator focuses on getting data to sales and ultimately the bom, this module focuses on getting data to the production order.  So any incompatibilities will be relatively small I'd think.

**Comment by ska-ibees** [comment]
Well, product configurator can create a blank BoM (If a BoM does not already exist) for each product variant. 
Anyways, let me check further how these two goodies can work together. 
But first could you please share any document/tutorial about the use case of mrp_dynamic_line? Or any implementation example to see how it works?
Thanks in advance!

**Comment by gdgellatly** [comment]
Hmm looks like I deleted the README and put in mrp_sale_fields by mistake.  The only other docs really is the demo data.  That has some sample products and BoM's.

**Comment by ska-ibees** [comment]
Alright, I will try to examine it on a a fresh install to avoid any conflict with other addons.
BTW, I am trying to achieve a manufacturing workflow where each sale order is unique in terms of final product sepcs and raw material used. 
Lets see how it goes...
