### ISSUE TITLE
Redirect URL should be set for for Azure login to work

### ISSUE THREAD

**Issue by chrisandrewmann** [odoonz/odoonz-addons#6]
Hi there,

Thanks so much for this module, really helps solve a key problem in allowing MS Graph / Azure authentication. Hope it gets merged into the official Odoo code soon.
I have it setup and working on our system however one area that wasn't mentioned in the readme was what to set the "Reply / Redirect URL" to in the Azure App Registration.
Needs to be set to: https://my-odoo-url/auth_oauth/signin

We also had to force resending the invitation email to all users on the system to link them to Azure.

**Comment by gdgellatly** [comment]
@chrisandrewmann I suppose it isn't. Someone else wrote the documentation, I just cut and paste it out of their bug report to Odoo, but setting redirect URL is same for all Oauth anyway, its not Azure specific or even flow specific. Just edit the README and make a PR if you want.

**Comment by chrisandrewmann** [comment]
Hi, thanks for your help.
I've done a PR as you suggested here: https://github.com/odoonz/odoonz-addons/pull/7
Will close this issue afterwards, or you can.
