### ISSUE TITLE
product_attribute_group Install error [v14]

### ISSUE THREAD

**Issue by sitolux** [odoonz/odoonz-addons#73]
## Hi there to the other side of the planet :-)
I just wounder if someone could tell me why there is an error while installing the module _product_attribute_group_ in **v14** 
I'd like to learn about how to debug..., I can read the code, but I'm still a noob in understanding how all this magic works ?-).
Any suggestions what is going wrong?
Thank you!

[product_attribute_group_install_error.txt](https://github.com/odoonz/odoonz-addons/files/6360142/product_attribute_group_install_error.txt)

**Comment by gdgellatly** [comment]
@sitolux I think you have old code. This error was resolved a while ago. Anyway, a lot of this repo is still in the process of migration over next 3-4 weeks, but that one should be OK.
