### ISSUE TITLE
Are the modules in the 15.0 branch really migrated?

### ISSUE THREAD

**Issue by BT-rmartin** [odoonz/odoonz-addons#79]
Dear @gdgellatly @chrisandrewmann,

We realized that you recently created the branch 15.0 with many modules. 
Are they really migrated or is this just a branch to have the basis to start the migration?
For instance, they have in the manifest 14.0, which is wrong, and they are not marked as installable:False in case they wouldn't be migrated.
Could you please clarify this?
Thanks in advance

**Comment by chrisandrewmann** [comment]
Hi @BT-rmartin, i'll leave @gdgellatly to respond as it's his Github repo but I believe they are not migrated yet.
As you say they all have v14 in their manifests still.
However I can confirm having tested auth_oauth_microsoft_graph in V15 and seems to be working well.
This is the only module i've had any involvement with so far.

**Comment by gdgellatly** [comment]
Nah, none of them are migrated yet. I only setup the branch for development last week and then a major come up. I'll update the installable flags later this week. When they are migrated the manifest will change version.

**Comment by BT-rmartin** [comment]
@gdgellatly I did check and the installable flags are still missing. Could you please add them?

**Comment by gdgellatly** [comment]
@BT-rmartin sorry I finally got around to this, actually paying client priorities and all. There won't be a lot of activity for v15, it is really just a stepping stone for us to v16 and no clients want to run v15 at this point, so beware, and of course welcome to make PR's.
